# Generated by Django 6.0.4 on 2026-05-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrateur',
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='statistique',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='lu',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='alerte',
            name='niveau',
            field=models.CharField(choices=[('orange', 'Attention - 80% budget atteint'), ('rouge', 'Budget depasse')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('revenu', 'Revenu'), ('depense', 'Depense')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='alerte',
            table='alerte',
        ),
        migrations.AlterModelTable(
            name='categorie',
            table='categorie',
        ),
        migrations.AlterModelTable(
            name='statistique',
            table='statistique',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
        migrations.AlterModelTable(
            name='utilisateur',
            table='utilisateur',
        ),
        migrations.DeleteModel(
            name='Chatbot',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='economie',
        ),
    ]
