# Generated by Django 6.0.4 on 2026-05-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_delete_administrateur_alter_categorie_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='niveau',
            field=models.CharField(choices=[('vert', 'OK - Budget respecte'), ('orange', 'Attention - 80% budget atteint'), ('rouge', 'Budget depasse')], max_length=10),
        ),
    ]
